version: "3.7"

services:
  kbot:
    #    image: dkzippa/prometheus-kbot:v1.0.10-6041fe0-linux-arm64
    image: dkzippa/prometheus-kbot:v1.0.11-5a35ca3-linux-amd64
    environment:
        - METRICS_HOST=otel-collector:4317
        - TELE_TOKEN=6760240824:AAEUYyqXzVlKw7pggKVHq1U6Aw6sy2Arb9Q

  fluent-bit:
    # curl "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'{ "query": { "match_all": {} }}'
    image: fluent/fluent-bit:latest    
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/filter.lua:/fluent-bit/bin/filter.lua
      - /var:/var
      - /proc:/host/proc
      - /sys:/host/sys
    ports:
      - "3001:3001"
    depends_on:
        - kbot

  loki:
    image: grafana/loki:2.9.0
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -log.level=error
    volumes:
      - ./loki/loki-local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8889:8889 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver
    depends_on:
      - loki
      - prometheus

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - loki
    ports:
      - 3333:3333    
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - GF_SERVER_HTTP_PORT=3333

  prometheus:    
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-conf.yml:/etc/prometheus/prometheus.yml      
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage      
    ports:
      - 9090:9090




  # grafana:
  #   environment:
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #   entrypoint:
  #     - sh
  #     - -euc
  #     - |
  #       mkdir -p /etc/grafana/provisioning/datasources
  #       cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
  #       apiVersion: 1
  #       datasources:
  #       - name: Loki
  #         type: loki
  #         access: proxy
  #         orgId: 1
  #         url: http://loki:3100
  #         basicAuth: false
  #         isDefault: true
  #         version: 1
  #         editable: false
  #       EOF
  #       /run.sh
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"