global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel_collector
    scrape_interval: 5s    
    metrics_path: /metrics
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

